"""changed constraints

Revision ID: c5de1e21d9bf
Revises: caeb9934b9eb
Create Date: 2026-01-18 00:17:10.323346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5de1e21d9bf'
down_revision: Union[str, Sequence[str], None] = 'caeb9934b9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notevault', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notevault', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notevault', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notevault', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
