"""update Note model

Revision ID: caeb9934b9eb
Revises: d7d3cf53ca30
Create Date: 2026-01-18 00:12:14.889170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeb9934b9eb'
down_revision: Union[str, Sequence[str], None] = 'd7d3cf53ca30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notevault', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notevault', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notevault', type_='foreignkey')
    op.drop_column('notevault', 'owner_id')
    # ### end Alembic commands ###
